name: Fortify AST Scan
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: Fortify AST Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fortify/github-action@ef5539bf4bd9c45c0bd971978f635a69eae55297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
